apiVersion: v1
kind: Service
metadata:
  name: {{ include "kogaro.fullname" . }}
  labels:
    {{- include "kogaro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kogaro.selectorLabels" . | nindent 4 }}