# Global settings
# Monitoring stack configuration for production environment.
global:
  domain: "ogaro.com"
  tls:
    enabled: true
    secretName: "kogaro-monitoring-tls"
    hosts:
      - alertmanager.ogaro.com
      - grafana.ogaro.com
      - prometheus.ogaro.com
  ingress:
    annotations:
      # SSL/TLS Configuration
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      
      # Security Headers
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains" always;
        more_set_headers "X-Content-Type-Options: nosniff" always;
        more_set_headers "X-Frame-Options: DENY" always;
        more_set_headers "X-XSS-Protection: 1; mode=block" always;
      
      # Proxy Settings
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    className: ingress-nginx

# Prometheus configuration
prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - prometheus.ogaro.com
    tls:
      - secretName: kogaro-monitoring-tls
        hosts:
          - prometheus.ogaro.com
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Prometheus"
      nginx.ingress.kubernetes.io/auth-secret: "prometheus-basic-auth"
      nginx.ingress.kubernetes.io/auth-type: "basic"
  prometheusSpec:
    resources:
      limits:
        cpu: 125m
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 100Mi
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

# Grafana configuration
grafana:
  enabled: true
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  ingress:
    enabled: true
    hosts:
      - grafana.ogaro.com
    tls:
      - secretName: kogaro-monitoring-tls
        hosts:
          - grafana.ogaro.com
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi

# Alertmanager configuration
alertmanager:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - alertmanager.ogaro.com
    tls:
      - secretName: kogaro-monitoring-tls
        hosts:
          - alertmanager.ogaro.com
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Alertmanager"
      nginx.ingress.kubernetes.io/auth-secret: "alertmanager-basic-auth"
      nginx.ingress.kubernetes.io/auth-type: "basic"
  alertmanagerSpec:
    resources:
      limits:
        cpu: 25m
        memory: 50Mi
      requests:
        cpu: 12m
        memory: 25Mi
    retention: 120h 