# Production ingress configurations for monitoring namespace
global:
  domain: "ogaro.com"
  tls:
    enabled: true
    secretName: "kogaro-monitoring-tls"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    className: ingress-nginx

prometheus:
  ingress:
    enabled: true
    hostname: "prometheus.${global.domain}"
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Prometheus"
      nginx.ingress.kubernetes.io/auth-secret: "prometheus-basic-auth"
      nginx.ingress.kubernetes.io/auth-type: "basic"

grafana:
  ingress:
    enabled: true
    hostname: "grafana.${global.domain}"

alertmanager:
  ingress:
    enabled: true
    hostname: "alertmanager.${global.domain}" 