# Global settings for test environment
global:
  domain: "ogaro.com"  # Same domain as production
  tls:
    enabled: true
    secretName: "kogaro-monitoring-test-tls"
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    className: ingress-nginx

# Prometheus configuration
prometheus:
  enabled: true
  ingress:
    enabled: true
    hostname: "prometheus-test.ogaro.com"
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Prometheus Test"
      nginx.ingress.kubernetes.io/auth-secret: "prometheus-test-basic-auth"
      nginx.ingress.kubernetes.io/auth-type: "basic"

# Grafana configuration
grafana:
  enabled: true
  ingress:
    enabled: true
    hostname: "grafana-test.ogaro.com"

# Alertmanager configuration
alertmanager:
  enabled: true
  ingress:
    enabled: true
    hostname: "alertmanager-test.ogaro.com" 