version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - shadow
    - revive
    - misspell
    - ineffassign
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
  
  disable:
    - funlen
    - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0