---
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - revive
    - misspell
    - ineffassign
    - errcheck
    - staticcheck
    - unused
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo

  disable:
    - funlen
    - lll

linters-settings:
  gocyclo:
    min-complexity: 45  # Allow main function complexity temporarily
  gosec:
    excludes:
      - G304  # Allow file path from variable (legitimate config file reading)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude duplication and constants in test files
    - path: "_test\\.go"
      linters:
        - dupl
        - goconst
    # Exclude subprocess in tests (legitimate test execution)
    - path: "main_test\\.go"
      linters:
        - gosec
