{{- if .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kogaro-bad-tls
  annotations:
    kogaro-test-case: "Ingress with TLS secret reference to non-existent Secret"
    kogaro-expected-error: "TLS Secret 'missing-tls-secret' referenced in Ingress does not exist"
spec:
  tls:
  - hosts:
    - secure.example.com
    secretName: missing-tls-secret
  rules:
  - host: secure.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kogaro-good-service
            port:
              number: 80
{{- end }}