{{- if .Values.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: kogaro-bad-secret-env
  annotations:
    kogaro-test-case: "Pod with Secret env var reference to non-existent Secret"
    kogaro-expected-error: "Secret 'missing-secret-key' referenced in env does not exist"
spec:
  containers:
  - name: test-container
    image: busybox:1.35
    command: ['sleep', '3600']
    env:
    - name: SECRET_VALUE
      valueFrom:
        secretKeyRef:
          name: missing-secret-key
          key: password
  restartPolicy: Never
{{- end }}