{{- if .Values.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: kogaro-bad-secret-volume
  annotations:
    kogaro-test-case: "Pod with Secret volume reference to non-existent Secret"
    kogaro-expected-error: "Secret 'missing-secret' referenced in volume does not exist"
spec:
  containers:
  - name: test-container
    image: busybox:1.35
    command: ['sleep', '3600']
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
  volumes:
  - name: secret-volume
    secret:
      secretName: missing-secret
  restartPolicy: Never
{{- end }}