{{- if .Values.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: kogaro-bad-pvc-ref
  annotations:
    kogaro-test-case: "Pod with PVC reference to non-existent PVC"
    kogaro-expected-error: "PVC 'missing-pvc' referenced in volume does not exist"
spec:
  containers:
  - name: test-container
    image: busybox:1.35
    command: ['sleep', '3600']
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: missing-pvc
  restartPolicy: Never
{{- end }}