{{- if .Values.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: kogaro-bad-secret-envfrom
  annotations:
    kogaro-test-case: "Pod with Secret envFrom reference to non-existent Secret"
    kogaro-expected-error: "Secret 'missing-env-secret' referenced in envFrom does not exist"
spec:
  containers:
  - name: test-container
    image: busybox:1.35
    command: ['sleep', '3600']
    envFrom:
    - secretRef:
        name: missing-env-secret
  restartPolicy: Never
{{- end }}