{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogaro-bad-serviceaccount
  annotations:
    kogaro-test-case: "Deployment with non-existent ServiceAccount"
    kogaro-expected-error: "ServiceAccount 'missing-sa' does not exist"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kogaro-bad-sa
  template:
    metadata:
      labels:
        app: kogaro-bad-sa
    spec:
      serviceAccountName: missing-sa
      automountServiceAccountToken: false
      containers:
      - name: test-container
        image: busybox:1.35
        command: ['sleep', '3600']
{{- end }}