apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kogaro-testbed.labels" . | nindent 4 }}
    test-case: "security-excessive-permissions"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-service-account-binding
  labels:
    {{- include "kogaro-testbed.labels" . | nindent 4 }}
    test-case: "security-excessive-permissions"
subjects:
- kind: ServiceAccount
  name: admin-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Granting cluster-admin role - should trigger validation error
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kogaro-testbed.labels" . | nindent 4 }}
    test-case: "security-excessive-permissions"
subjects:
- kind: ServiceAccount
  name: admin-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admin  # Granting admin role - should trigger validation error
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: excessive-permissions-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kogaro-testbed.labels" . | nindent 4 }}
    test-case: "security-excessive-permissions"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excessive-permissions-app
  template:
    metadata:
      labels:
        app: excessive-permissions-app
    spec:
      serviceAccountName: admin-service-account  # Using the overly privileged ServiceAccount
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: app-container
        image: nginx:latest
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"