apiVersion: v1
kind: Service
metadata:
  name: kogaro-bad-service
  annotations:
    kogaro-test-case: "Service with non-matching selector"
    kogaro-expected-error: "No pods match service selector"
spec:
  selector:
    app: no-such-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
