apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogaro
  namespace: kogaro-system
  labels:
    app: kogaro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kogaro
  template:
    metadata:
      labels:
        app: kogaro
    spec:
      serviceAccountName: kogaro
      containers:
      - name: manager
        image: kogaro:latest
        imagePullPolicy: IfNotPresent
        args:
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        - --leader-elect=true
        - --scan-interval=5m
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kogaro
  namespace: kogaro-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kogaro
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kogaro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kogaro
subjects:
- kind: ServiceAccount
  name: kogaro
  namespace: kogaro-system
---
apiVersion: v1
kind: Service
metadata:
  name: kogaro-metrics
  namespace: kogaro-system
  labels:
    app: kogaro
spec:
  selector:
    app: kogaro
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
  name: kogaro-system