# Default values for kogaro-website
replicaCount: 2

image:
  repository: registry.ogaro.com/kogaro-website
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-http01"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-compression: "true"
    nginx.ingress.kubernetes.io/compression-level: "6"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
  hosts:
    - host: kogaro.com
      paths:
        - path: /
          pathType: Prefix
    - host: www.kogaro.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kogaro-website-tls
      hosts:
        - kogaro.com
        - www.kogaro.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

podSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - kogaro-website
          topologyKey: kubernetes.io/hostname

nodeSelector: {}

tolerations: []

# Registry credentials (created separately as K8s secret)
registry:
  secretName: regcred