replicaCount: 1

image:
  repository: topiaruss/kogaro
  pullPolicy: IfNotPresent
  tag: "0.1.1"

imagePullSecrets: []
  # - name: myregistrykey
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

service:
  type: ClusterIP
  port: 8080
  metricsPort: 8080
  healthPort: 8081

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Validation configuration
validation:
  enableIngressValidation: true
  enableConfigMapValidation: true
  enableSecretValidation: true
  enablePVCValidation: true
  enableServiceAccountValidation: false
  scanInterval: "5m"

# Metrics configuration
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics

# RBAC configuration
rbac:
  create: true
