apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-kube-prometheus-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
  annotations:
    {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.alertmanager.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: alertmanager-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  tls:
    - hosts:
        - {{ (index .Values.alertmanager.ingress.hosts 0) }}
      secretName: {{ .Values.global.tls.secretName }}
  rules:
    - host: {{ (index .Values.alertmanager.ingress.hosts 0) }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kube-prometheus-alertmanager
                port:
                  number: 9093 