apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-tls
  namespace: monitoring
spec:
  secretName: kogaro-monitoring-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prometheus.ogaro.com
    - grafana.ogaro.com
    - alertmanager.ogaro.com 