// @ts-check
// This file is automatically generated. DO NOT EDIT

export function Scan() {
    return window['go']['main']['App']['Scan']();
}

export function GetNodeDetail(arg1) {
    return window['go']['main']['App']['GetNodeDetail'](arg1);
}

export function ExpandNode(arg1) {
    return window['go']['main']['App']['ExpandNode'](arg1);
}

export function GetKubeContexts() {
    return window['go']['main']['App']['GetKubeContexts']();
}

export function GetCurrentContext() {
    return window['go']['main']['App']['GetCurrentContext']();
}

export function SwitchContext(arg1) {
    return window['go']['main']['App']['SwitchContext'](arg1);
}

export function GetFixPlan(arg1) {
    return window['go']['main']['App']['GetFixPlan'](arg1);
}

export function GetScanHistory(arg1) {
    return window['go']['main']['App']['GetScanHistory'](arg1);
}

export function GetScanDiff(arg1, arg2) {
    return window['go']['main']['App']['GetScanDiff'](arg1, arg2);
}

export function ApplyFix(arg1) {
    return window['go']['main']['App']['ApplyFix'](arg1);
}

export function RunCommand(arg1, arg2) {
    return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function RecordFixAttempt(arg1) {
    return window['go']['main']['App']['RecordFixAttempt'](arg1);
}

export function GetBuildInfo() {
    return window['go']['main']['App']['GetBuildInfo']();
}
