// @ts-check
// This file is automatically generated. DO NOT EDIT

export function Scan() {
    return window['go']['main']['App']['Scan']();
}

export function GetNodeDetail(arg1) {
    return window['go']['main']['App']['GetNodeDetail'](arg1);
}

export function ExpandNode(arg1) {
    return window['go']['main']['App']['ExpandNode'](arg1);
}

export function GetKubeContexts() {
    return window['go']['main']['App']['GetKubeContexts']();
}

export function GetCurrentContext() {
    return window['go']['main']['App']['GetCurrentContext']();
}

export function SwitchContext(arg1) {
    return window['go']['main']['App']['SwitchContext'](arg1);
}
