// This file is automatically generated. DO NOT EDIT

import { graph } from '../models';

export function Scan(): Promise<graph.FaultGraph>;
export function GetNodeDetail(nodeID: string): Promise<graph.NodeDetailResponse>;
export function ExpandNode(nodeID: string): Promise<graph.FaultGraph>;
export function GetKubeContexts(): Promise<string[]>;
export function GetCurrentContext(): Promise<string>;
export function SwitchContext(contextName: string): Promise<void>;
